### ISSUE TITLE
Unit tests prevent code from compiling.

### ISSUE THREAD

**Issue by dariusstrasel** [mechamecho/DataDrivenTesting#2]
Hi Nafissa,

I pulled the latest changes and noticed the build/solution isn't compiling anymore. It looks like the unit tests are raising compile time errors. Maybe something to look into?

Last build using commit: 9059d34a0831536191f1646ffdedbc1f1fc2a513

- Darius

**Comment by mechamecho** [comment]
Which commit was the last working commit?

**Comment by dariusstrasel** [comment]
6426df02300f6533674849a15a961be575befcec was last working commit.

The PR merge (da8985204caf790acc026fcb0d1eddb538d1b215) introduced the build errors. Most likely something I did when I wrote the tests. ;)

**Comment by dariusstrasel** [comment]
@mechamecho I'll leave this decision to you. Which one better reflects the design of the code?

**Comment by mechamecho** [comment]
Makes sense. I was thinking that it probably is better to make the JSONFile and JSONFileReader classes more flexible so that they can be reused for future testing projects. However, this situation is different, since these Unit Tests are designed to test these classes as if they are the project to be tested. In this case, I will adjust the tests to test my design of those classes as it is.

**Comment by dariusstrasel** [comment]
Build errors are resolved as of: 5d2be84

Closing issue.
